var litleTransaction_v8_29_Module_Factory = function () {
  var litleTransaction_v8_29 = {
    name: 'litleTransaction_v8_29',
    defaultElementNamespaceURI: 'http:\/\/www.litle.com\/schema',
    typeInfos: [{
        localName: 'CustomBilling',
        typeName: null,
        propertyInfos: [{
            name: 'url'
          }, {
            name: 'city'
          }, {
            name: 'phone'
          }, {
            name: 'descriptor'
          }]
      }, {
        localName: 'DepositReversalResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'VirtualGiftCardResponse',
        typeName: null,
        propertyInfos: [{
            name: 'accountNumber'
          }, {
            name: 'cardValidationNum'
          }]
      }, {
        localName: 'AuthReversalResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'RefundReversalResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'Credit',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'amount',
            typeInfo: 'Integer'
          }, {
            name: 'secondaryAmount',
            typeInfo: 'Integer'
          }, {
            name: 'surchargeAmount',
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'billToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'paypal',
            required: true,
            typeInfo: '.Credit.Paypal'
          }, {
            name: 'paypage',
            required: true,
            typeInfo: '.CardPaypageType'
          }, {
            name: 'token',
            required: true,
            typeInfo: '.CardTokenType'
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }, {
            name: 'mpos',
            required: true,
            typeInfo: '.MposType'
          }, {
            name: 'customBilling',
            typeInfo: '.CustomBilling'
          }, {
            name: 'taxType',
            typeInfo: '.GovtTaxTypeEnum'
          }, {
            name: 'billMeLaterRequest',
            typeInfo: '.BillMeLaterRequest'
          }, {
            name: 'enhancedData',
            typeInfo: '.EnhancedData'
          }, {
            name: 'processingInstructions',
            typeInfo: '.ProcessingInstructions'
          }, {
            name: 'pos',
            typeInfo: '.Pos'
          }, {
            name: 'amexAggregatorData',
            typeInfo: '.AmexAggregatorData'
          }, {
            name: 'merchantData',
            typeInfo: '.MerchantDataType'
          }, {
            name: 'payPalNotes'
          }, {
            name: 'actionReason'
          }]
      }, {
        localName: 'Activate',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'virtualGiftCard',
            required: true,
            typeInfo: '.VirtualGiftCardType'
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }]
      }, {
        localName: 'LoadReversalResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'TransactionTypeWithReportGroup',
        typeName: 'transactionTypeWithReportGroup',
        baseTypeInfo: '.TransactionType',
        propertyInfos: [{
            name: 'reportGroup',
            required: true,
            attributeName: {
              localPart: 'reportGroup'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'CreatePlan',
        typeName: null,
        baseTypeInfo: '.RecurringTransactionType',
        propertyInfos: [{
            name: 'planCode',
            required: true
          }, {
            name: 'name',
            required: true
          }, {
            name: 'description'
          }, {
            name: 'intervalType',
            required: true,
            typeInfo: '.IntervalTypeEnum'
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'numberOfPayments',
            typeInfo: 'Integer'
          }, {
            name: 'trialNumberOfIntervals',
            typeInfo: 'Integer'
          }, {
            name: 'trialIntervalType',
            typeInfo: '.TrialIntervalTypeEnum'
          }, {
            name: 'active',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'Wallet',
        typeName: null,
        propertyInfos: [{
            name: 'walletSourceType',
            required: true,
            typeInfo: '.WalletSourceType'
          }, {
            name: 'walletSourceTypeId',
            required: true
          }]
      }, {
        localName: 'EcheckCredit',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'amount',
            typeInfo: 'Integer'
          }, {
            name: 'secondaryAmount',
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'billToAddress',
            required: true,
            typeInfo: '.Contact'
          }, {
            name: 'echeckOrEcheckToken',
            required: true,
            mixed: false,
            allowDom: false,
            typeInfo: 'AnyType',
            type: 'elementRef'
          }, {
            name: 'customBilling',
            typeInfo: '.CustomBilling'
          }, {
            name: 'merchantData',
            typeInfo: '.MerchantDataType'
          }]
      }, {
        localName: 'CreatePlanResponse',
        typeName: null,
        baseTypeInfo: '.RecurringTransactionResponseType',
        propertyInfos: [{
            name: 'planCode',
            required: true
          }]
      }, {
        localName: 'RecurringTransactionType',
        typeName: 'recurringTransactionType'
      }, {
        localName: 'DetailTax',
        typeName: null,
        propertyInfos: [{
            name: 'taxIncludedInTotal',
            typeInfo: 'Boolean'
          }, {
            name: 'taxAmount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'taxRate',
            typeInfo: 'Decimal'
          }, {
            name: 'taxTypeIdentifier',
            values: ['00', '01', '02', '03', '04', '05', '06', '10', '11', '12', '13', '14', '20', '21', '22']
          }, {
            name: 'cardAcceptorTaxId'
          }]
      }, {
        localName: 'CardPaypageType',
        typeName: 'cardPaypageType',
        propertyInfos: [{
            name: 'paypageRegistrationId',
            required: true
          }, {
            name: 'expDate'
          }, {
            name: 'cardValidationNum'
          }, {
            name: 'type',
            values: ['MC', 'VI', 'AX', 'DC', 'DI', 'PP', 'JC', 'BL', 'EC', 'GC', '']
          }]
      }, {
        localName: 'BillMeLaterRequest',
        typeName: null,
        propertyInfos: [{
            name: 'bmlMerchantId',
            typeInfo: 'Long'
          }, {
            name: 'bmlProductType'
          }, {
            name: 'termsAndConditions',
            typeInfo: 'Int'
          }, {
            name: 'preapprovalNumber'
          }, {
            name: 'merchantPromotionalCode',
            typeInfo: 'Int'
          }, {
            name: 'customerPasswordChanged',
            typeInfo: 'Boolean'
          }, {
            name: 'customerBillingAddressChanged',
            typeInfo: 'Boolean'
          }, {
            name: 'customerEmailChanged',
            typeInfo: 'Boolean'
          }, {
            name: 'customerPhoneChanged',
            typeInfo: 'Boolean'
          }, {
            name: 'secretQuestionCode'
          }, {
            name: 'secretQuestionAnswer'
          }, {
            name: 'virtualAuthenticationKeyPresenceIndicator'
          }, {
            name: 'virtualAuthenticationKeyData'
          }, {
            name: 'itemCategoryCode',
            typeInfo: 'Int'
          }, {
            name: 'authorizationSourcePlatform'
          }]
      }, {
        localName: 'PayPal',
        typeName: 'payPal',
        propertyInfos: [{
            name: 'payerId',
            required: true
          }, {
            name: 'token'
          }, {
            name: 'transactionId',
            required: true
          }]
      }, {
        localName: 'HealthcareAmounts',
        typeName: null,
        propertyInfos: [{
            name: 'totalHealthcareAmount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'rxAmount',
            elementName: 'RxAmount',
            typeInfo: 'Integer'
          }, {
            name: 'visionAmount',
            typeInfo: 'Integer'
          }, {
            name: 'clinicOtherAmount',
            typeInfo: 'Integer'
          }, {
            name: 'dentalAmount',
            typeInfo: 'Integer'
          }]
      }, {
        localName: 'CardAccountInfoType',
        typeName: 'cardAccountInfoType',
        propertyInfos: [{
            name: 'type',
            required: true,
            values: ['MC', 'VI', 'AX', 'DC', 'DI', 'PP', 'JC', 'BL', 'EC', 'GC', '']
          }, {
            name: 'number',
            required: true
          }, {
            name: 'expDate',
            required: true
          }]
      }, {
        localName: 'RecurringSubscriptionType',
        typeName: 'recurringSubscriptionType',
        propertyInfos: [{
            name: 'planCode',
            required: true
          }, {
            name: 'numberOfPayments',
            typeInfo: 'Integer'
          }, {
            name: 'startDate',
            typeInfo: 'Date'
          }, {
            name: 'amount',
            typeInfo: 'Integer'
          }, {
            name: 'createDiscounts',
            minOccurs: 0,
            collection: true,
            elementName: 'createDiscount',
            typeInfo: '.CreateDiscountType'
          }, {
            name: 'createAddOns',
            minOccurs: 0,
            collection: true,
            elementName: 'createAddOn',
            typeInfo: '.CreateAddOnType'
          }]
      }, {
        localName: 'UpdateCardValidationNumOnTokenResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId'
          }, {
            name: 'response',
            required: true
          }, {
            name: 'message',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'DeactivateResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'approvedAmount',
            typeInfo: 'Integer'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'ActivateResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }, {
            name: 'virtualGiftCardResponse',
            typeInfo: '.VirtualGiftCardResponse'
          }, {
            name: 'duplicate',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'duplicate'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'UpdateSubscriptionResponse',
        typeName: null,
        baseTypeInfo: '.RecurringTransactionResponseType',
        propertyInfos: [{
            name: 'subscriptionId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }]
      }, {
        localName: 'VirtualGiftCardType',
        typeName: 'virtualGiftCardType',
        propertyInfos: [{
            name: 'accountNumberLength',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'giftCardBin',
            required: true
          }]
      }, {
        localName: 'ApplepayHeaderType',
        typeName: 'applepayHeaderType',
        propertyInfos: [{
            name: 'applicationData',
            required: true
          }, {
            name: 'ephemeralPublicKey',
            required: true
          }, {
            name: 'publicKeyHash',
            required: true
          }, {
            name: 'transactionId',
            required: true
          }]
      }, {
        localName: 'BalanceInquiry',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }]
      }, {
        localName: 'CreditResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId'
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }, {
            name: 'duplicate',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'duplicate'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'AdvancedFraudResultsType',
        typeName: 'advancedFraudResultsType',
        propertyInfos: [{
            name: 'deviceReviewStatus'
          }, {
            name: 'deviceReputationScore',
            typeInfo: 'Int'
          }, {
            name: 'triggeredRules',
            minOccurs: 0,
            collection: true,
            elementName: 'triggeredRule'
          }]
      }, {
        localName: 'ApplepayResponse',
        typeName: null,
        propertyInfos: [{
            name: 'applicationPrimaryAccountNumber'
          }, {
            name: 'applicationExpirationDate'
          }, {
            name: 'currencyCode'
          }, {
            name: 'transactionAmount',
            typeInfo: 'Integer'
          }, {
            name: 'cardholderName'
          }, {
            name: 'deviceManufacturerIdentifier'
          }, {
            name: 'paymentDataType'
          }, {
            name: 'onlinePaymentCryptogram',
            typeInfo: 'Base64Binary'
          }, {
            name: 'eciIndicator'
          }]
      }, {
        localName: 'TokenResponseType',
        typeName: 'tokenResponseType',
        propertyInfos: [{
            name: 'litleToken'
          }, {
            name: 'tokenResponseCode',
            required: true
          }, {
            name: 'tokenMessage',
            required: true
          }, {
            name: 'type',
            values: ['MC', 'VI', 'AX', 'DC', 'DI', 'PP', 'JC', 'BL', 'EC', 'GC', '']
          }, {
            name: 'bin'
          }, {
            name: 'eCheckAccountSuffix'
          }]
      }, {
        localName: 'RecurringResponseType',
        typeName: 'recurringResponseType',
        propertyInfos: [{
            name: 'subscriptionId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'responseCode',
            required: true
          }, {
            name: 'responseMessage',
            required: true
          }, {
            name: 'recurringTxnId',
            typeInfo: 'Long'
          }]
      }, {
        localName: 'TransactionTypeOptionReportGroup',
        typeName: 'transactionTypeOptionReportGroup',
        baseTypeInfo: '.TransactionType',
        propertyInfos: [{
            name: 'reportGroup',
            attributeName: {
              localPart: 'reportGroup'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'UpdateCardValidationNumOnToken',
        typeName: 'updateCardValidationNumOnToken',
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId'
          }, {
            name: 'litleToken',
            required: true
          }, {
            name: 'cardValidationNum',
            required: true
          }]
      }, {
        localName: 'UpdateSubscription',
        typeName: null,
        baseTypeInfo: '.RecurringTransactionType',
        propertyInfos: [{
            name: 'subscriptionId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'planCode'
          }, {
            name: 'billToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'paypage',
            required: true,
            typeInfo: '.CardPaypageType'
          }, {
            name: 'token',
            required: true,
            typeInfo: '.CardTokenType'
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }, {
            name: 'billingDate',
            typeInfo: 'Date'
          }, {
            name: 'createDiscounts',
            minOccurs: 0,
            collection: true,
            elementName: 'createDiscount',
            typeInfo: '.CreateDiscountType'
          }, {
            name: 'updateDiscounts',
            minOccurs: 0,
            collection: true,
            elementName: 'updateDiscount',
            typeInfo: '.UpdateDiscountType'
          }, {
            name: 'deleteDiscounts',
            minOccurs: 0,
            collection: true,
            elementName: 'deleteDiscount',
            typeInfo: '.DeleteDiscountType'
          }, {
            name: 'createAddOns',
            minOccurs: 0,
            collection: true,
            elementName: 'createAddOn',
            typeInfo: '.CreateAddOnType'
          }, {
            name: 'updateAddOns',
            minOccurs: 0,
            collection: true,
            elementName: 'updateAddOn',
            typeInfo: '.UpdateAddOnType'
          }, {
            name: 'deleteAddOns',
            minOccurs: 0,
            collection: true,
            elementName: 'deleteAddOn',
            typeInfo: '.DeleteAddOnType'
          }]
      }, {
        localName: 'AuthorizationResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'cardProductId'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'authCode'
          }, {
            name: 'authorizationResponseSubCode'
          }, {
            name: 'approvedAmount',
            typeInfo: 'Integer'
          }, {
            name: 'accountInformation',
            typeInfo: '.AccountInfoType'
          }, {
            name: 'accountUpdater',
            typeInfo: '.AccountUpdater'
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'billMeLaterResponseData',
            typeInfo: '.BillMeLaterResponseData'
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }, {
            name: 'enhancedAuthResponse',
            typeInfo: '.EnhancedAuthResponse'
          }, {
            name: 'recycling',
            typeInfo: '.RecyclingType'
          }, {
            name: 'recurringResponse',
            typeInfo: '.RecurringResponseType'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }, {
            name: 'applepayResponse',
            typeInfo: '.ApplepayResponse'
          }]
      }, {
        localName: 'EcheckRedeposit',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'echeckOrEcheckToken',
            mixed: false,
            allowDom: false,
            typeInfo: 'AnyType',
            type: 'elementRef'
          }, {
            name: 'merchantData',
            typeInfo: '.MerchantDataType'
          }]
      }, {
        localName: 'AuthInformation',
        typeName: null,
        propertyInfos: [{
            name: 'authDate',
            required: true,
            typeInfo: 'Date'
          }, {
            name: 'authCode',
            required: true
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'authAmount',
            typeInfo: 'Integer'
          }]
      }, {
        localName: 'DeleteAddOnType',
        typeName: 'deleteAddOnType',
        propertyInfos: [{
            name: 'addOnCode',
            required: true
          }]
      }, {
        localName: 'Pos',
        typeName: null,
        propertyInfos: [{
            name: 'capability',
            required: true,
            typeInfo: '.PosCapabilityTypeEnum'
          }, {
            name: 'entryMode',
            required: true,
            typeInfo: '.PosEntryModeTypeEnum'
          }, {
            name: 'cardholderId',
            required: true,
            typeInfo: '.PosCardholderIdTypeEnum'
          }, {
            name: 'terminalId'
          }, {
            name: 'catLevel',
            typeInfo: '.PosCatLevelEnum'
          }]
      }, {
        localName: 'RecurringRequestType',
        typeName: 'recurringRequestType',
        propertyInfos: [{
            name: 'subscription',
            required: true,
            typeInfo: '.RecurringSubscriptionType'
          }]
      }, {
        localName: 'CreateAddOnType',
        typeName: 'createAddOnType',
        propertyInfos: [{
            name: 'addOnCode',
            required: true
          }, {
            name: 'name',
            required: true
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'startDate',
            required: true,
            typeInfo: 'Date'
          }, {
            name: 'endDate',
            required: true,
            typeInfo: 'Date'
          }]
      }, {
        localName: 'ForceCaptureResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }, {
            name: 'accountUpdater',
            typeInfo: '.AccountUpdater'
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'EcheckType',
        typeName: 'echeckType',
        propertyInfos: [{
            name: 'accType',
            required: true,
            typeInfo: '.EcheckAccountTypeEnum'
          }, {
            name: 'accNum',
            required: true
          }, {
            name: 'routingNum',
            required: true
          }, {
            name: 'checkNum'
          }]
      }, {
        localName: 'UpdatePlan',
        typeName: null,
        baseTypeInfo: '.RecurringTransactionType',
        propertyInfos: [{
            name: 'planCode',
            required: true
          }, {
            name: 'active',
            required: true,
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'EcheckRedepositResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'accountUpdater',
            typeInfo: '.AccountUpdater'
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }]
      }, {
        localName: 'RegisterTokenRequestType',
        typeName: 'registerTokenRequestType',
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId'
          }, {
            name: 'applepay',
            required: true,
            typeInfo: '.ApplepayType'
          }, {
            name: 'paypageRegistrationId',
            required: true
          }, {
            name: 'echeckForToken',
            required: true,
            typeInfo: '.EcheckForTokenType'
          }, {
            name: 'accountNumber',
            required: true
          }, {
            name: 'mpos',
            required: true,
            typeInfo: '.MposType'
          }, {
            name: 'cardValidationNum'
          }]
      }, {
        localName: 'EnhancedData',
        typeName: null,
        propertyInfos: [{
            name: 'customerReference'
          }, {
            name: 'salesTax',
            typeInfo: 'Integer'
          }, {
            name: 'deliveryType',
            values: ['CNC', 'DIG', 'PHY', 'SVC', 'TBD']
          }, {
            name: 'taxExempt',
            typeInfo: 'Boolean'
          }, {
            name: 'discountAmount',
            typeInfo: 'Integer'
          }, {
            name: 'shippingAmount',
            typeInfo: 'Integer'
          }, {
            name: 'dutyAmount',
            typeInfo: 'Integer'
          }, {
            name: 'shipFromPostalCode'
          }, {
            name: 'destinationPostalCode'
          }, {
            name: 'destinationCountryCode',
            typeInfo: '.CountryTypeEnum'
          }, {
            name: 'invoiceReferenceNumber'
          }, {
            name: 'orderDate',
            typeInfo: 'Date'
          }, {
            name: 'detailTaxes',
            minOccurs: 0,
            maxOccurs: 6,
            collection: true,
            elementName: 'detailTax',
            typeInfo: '.DetailTax'
          }, {
            name: 'lineItemDatas',
            minOccurs: 0,
            maxOccurs: 99,
            collection: true,
            elementName: 'lineItemData',
            typeInfo: '.LineItemData'
          }]
      }, {
        localName: 'Authorization',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'secondaryAmount',
            typeInfo: 'Integer'
          }, {
            name: 'surchargeAmount',
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'customerInfo',
            typeInfo: '.CustomerInfo'
          }, {
            name: 'billToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'shipToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'applepay',
            required: true,
            typeInfo: '.ApplepayType'
          }, {
            name: 'paypage',
            required: true,
            typeInfo: '.CardPaypageType'
          }, {
            name: 'token',
            required: true,
            typeInfo: '.CardTokenType'
          }, {
            name: 'paypal',
            required: true,
            typeInfo: '.PayPal'
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }, {
            name: 'mpos',
            required: true,
            typeInfo: '.MposType'
          }, {
            name: 'billMeLaterRequest',
            typeInfo: '.BillMeLaterRequest'
          }, {
            name: 'cardholderAuthentication',
            typeInfo: '.FraudCheckType'
          }, {
            name: 'processingInstructions',
            typeInfo: '.ProcessingInstructions'
          }, {
            name: 'pos',
            typeInfo: '.Pos'
          }, {
            name: 'customBilling',
            typeInfo: '.CustomBilling'
          }, {
            name: 'taxType',
            typeInfo: '.GovtTaxTypeEnum'
          }, {
            name: 'enhancedData',
            typeInfo: '.EnhancedData'
          }, {
            name: 'amexAggregatorData',
            typeInfo: '.AmexAggregatorData'
          }, {
            name: 'allowPartialAuth',
            typeInfo: 'Boolean'
          }, {
            name: 'healthcareIIAS',
            typeInfo: '.HealthcareIIAS'
          }, {
            name: 'filtering',
            typeInfo: '.FilteringType'
          }, {
            name: 'merchantData',
            typeInfo: '.MerchantDataType'
          }, {
            name: 'recyclingRequest',
            typeInfo: '.RecyclingRequestType'
          }, {
            name: 'fraudFilterOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'recurringRequest',
            typeInfo: '.RecurringRequestType'
          }, {
            name: 'debtRepayment',
            typeInfo: 'Boolean'
          }, {
            name: 'advancedFraudChecks',
            typeInfo: '.AdvancedFraudChecksType'
          }, {
            name: 'wallet',
            typeInfo: '.Wallet'
          }, {
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }]
      }, {
        localName: 'TransactionTypeWithReportGroupAndPartial',
        typeName: 'transactionTypeWithReportGroupAndPartial',
        baseTypeInfo: '.TransactionType',
        propertyInfos: [{
            name: 'reportGroup',
            required: true,
            attributeName: {
              localPart: 'reportGroup'
            },
            type: 'attribute'
          }, {
            name: 'partial',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'partial'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'EcheckSalesResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId'
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'verificationCode'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'accountUpdater',
            typeInfo: '.AccountUpdater'
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }, {
            name: 'duplicate',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'duplicate'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Authentication',
        typeName: null,
        propertyInfos: [{
            name: 'user',
            required: true
          }, {
            name: 'password',
            required: true
          }]
      }, {
        localName: 'EcheckForTokenType',
        typeName: 'echeckForTokenType',
        propertyInfos: [{
            name: 'accNum',
            required: true
          }, {
            name: 'routingNum',
            required: true
          }]
      }, {
        localName: 'Contact',
        typeName: 'contact',
        propertyInfos: [{
            name: 'name'
          }, {
            name: 'firstName'
          }, {
            name: 'middleInitial'
          }, {
            name: 'lastName'
          }, {
            name: 'companyName'
          }, {
            name: 'addressLine1'
          }, {
            name: 'addressLine2'
          }, {
            name: 'addressLine3'
          }, {
            name: 'city'
          }, {
            name: 'state'
          }, {
            name: 'zip'
          }, {
            name: 'country',
            typeInfo: '.CountryTypeEnum'
          }, {
            name: 'email'
          }, {
            name: 'phone'
          }]
      }, {
        localName: 'CaptureGivenAuth',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'authInformation',
            required: true,
            typeInfo: '.AuthInformation'
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'secondaryAmount',
            typeInfo: 'Integer'
          }, {
            name: 'surchargeAmount',
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'billToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'shipToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'paypage',
            required: true,
            typeInfo: '.CardPaypageType'
          }, {
            name: 'token',
            required: true,
            typeInfo: '.CardTokenType'
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }, {
            name: 'mpos',
            required: true,
            typeInfo: '.MposType'
          }, {
            name: 'customBilling',
            typeInfo: '.CustomBilling'
          }, {
            name: 'taxType',
            typeInfo: '.GovtTaxTypeEnum'
          }, {
            name: 'billMeLaterRequest',
            typeInfo: '.BillMeLaterRequest'
          }, {
            name: 'enhancedData',
            typeInfo: '.EnhancedData'
          }, {
            name: 'processingInstructions',
            typeInfo: '.ProcessingInstructions'
          }, {
            name: 'pos',
            typeInfo: '.Pos'
          }, {
            name: 'amexAggregatorData',
            typeInfo: '.AmexAggregatorData'
          }, {
            name: 'merchantData',
            typeInfo: '.MerchantDataType'
          }, {
            name: 'debtRepayment',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'SaleResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'cardProductId'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'authCode'
          }, {
            name: 'authorizationResponseSubCode'
          }, {
            name: 'approvedAmount',
            typeInfo: 'Integer'
          }, {
            name: 'accountInformation',
            typeInfo: '.AccountInfoType'
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'billMeLaterResponseData',
            typeInfo: '.BillMeLaterResponseData'
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }, {
            name: 'enhancedAuthResponse',
            typeInfo: '.EnhancedAuthResponse'
          }, {
            name: 'accountUpdater',
            typeInfo: '.AccountUpdater'
          }, {
            name: 'recycling',
            typeInfo: '.RecyclingType'
          }, {
            name: 'recurringResponse',
            typeInfo: '.RecurringResponseType'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }, {
            name: 'applepayResponse',
            typeInfo: '.ApplepayResponse'
          }, {
            name: 'duplicate',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'duplicate'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'FraudCheck',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'advancedFraudChecks',
            required: true,
            typeInfo: '.AdvancedFraudChecksType'
          }]
      }, {
        localName: 'LitleInternalRecurringRequestType',
        typeName: 'litleInternalRecurringRequestType',
        propertyInfos: [{
            name: 'subscriptionId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'recurringTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'finalPayment',
            required: true,
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'UnloadReversalResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'CardTokenType',
        typeName: 'cardTokenType',
        propertyInfos: [{
            name: 'litleToken',
            required: true
          }, {
            name: 'expDate'
          }, {
            name: 'cardValidationNum'
          }, {
            name: 'type',
            values: ['MC', 'VI', 'AX', 'DC', 'DI', 'PP', 'JC', 'BL', 'EC', 'GC', '']
          }]
      }, {
        localName: 'CardTokenInfoType',
        typeName: 'cardTokenInfoType',
        propertyInfos: [{
            name: 'litleToken',
            required: true
          }, {
            name: 'type',
            required: true,
            values: ['MC', 'VI', 'AX', 'DC', 'DI', 'PP', 'JC', 'BL', 'EC', 'GC', '']
          }, {
            name: 'expDate',
            required: true
          }, {
            name: 'bin'
          }]
      }, {
        localName: 'EcheckCreditResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId'
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'accountUpdater',
            typeInfo: '.AccountUpdater'
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }, {
            name: 'duplicate',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'duplicate'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'Unload',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }]
      }, {
        localName: 'TransactionType',
        typeName: 'transactionType',
        propertyInfos: [{
            name: 'id',
            attributeName: {
              localPart: 'id'
            },
            type: 'attribute'
          }, {
            name: 'customerId',
            attributeName: {
              localPart: 'customerId'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'FraudResult',
        typeName: null,
        propertyInfos: [{
            name: 'avsResult'
          }, {
            name: 'cardValidationResult'
          }, {
            name: 'authenticationResult'
          }, {
            name: 'advancedAVSResult'
          }, {
            name: 'advancedFraudResults',
            typeInfo: '.AdvancedFraudResultsType'
          }]
      }, {
        localName: 'RecyclingRequestType',
        typeName: 'recyclingRequestType',
        propertyInfos: [{
            name: 'recycleBy',
            typeInfo: '.RecycleByTypeEnum'
          }, {
            name: 'recycleId'
          }]
      }, {
        localName: 'ForceCapture',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'secondaryAmount',
            typeInfo: 'Integer'
          }, {
            name: 'surchargeAmount',
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'billToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'paypage',
            required: true,
            typeInfo: '.CardPaypageType'
          }, {
            name: 'token',
            required: true,
            typeInfo: '.CardTokenType'
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }, {
            name: 'mpos',
            required: true,
            typeInfo: '.MposType'
          }, {
            name: 'customBilling',
            typeInfo: '.CustomBilling'
          }, {
            name: 'taxType',
            typeInfo: '.GovtTaxTypeEnum'
          }, {
            name: 'enhancedData',
            typeInfo: '.EnhancedData'
          }, {
            name: 'processingInstructions',
            typeInfo: '.ProcessingInstructions'
          }, {
            name: 'pos',
            typeInfo: '.Pos'
          }, {
            name: 'amexAggregatorData',
            typeInfo: '.AmexAggregatorData'
          }, {
            name: 'merchantData',
            typeInfo: '.MerchantDataType'
          }, {
            name: 'debtRepayment',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'UpdateDiscountType',
        typeName: 'updateDiscountType',
        propertyInfos: [{
            name: 'discountCode',
            required: true
          }, {
            name: 'name'
          }, {
            name: 'amount',
            typeInfo: 'Integer'
          }, {
            name: 'startDate',
            typeInfo: 'Date'
          }, {
            name: 'endDate',
            typeInfo: 'Date'
          }]
      }, {
        localName: 'GiftCardResponse',
        typeName: null,
        propertyInfos: [{
            name: 'availableBalance'
          }, {
            name: 'beginningBalance'
          }, {
            name: 'endingBalance'
          }, {
            name: 'cashBackAmount'
          }]
      }, {
        localName: 'Deactivate',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }]
      }, {
        localName: 'Load',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }]
      }, {
        localName: 'RegisterTokenResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId'
          }, {
            name: 'litleToken'
          }, {
            name: 'bin'
          }, {
            name: 'type',
            values: ['MC', 'VI', 'AX', 'DC', 'DI', 'PP', 'JC', 'BL', 'EC', 'GC', '']
          }, {
            name: 'eCheckAccountSuffix'
          }, {
            name: 'response',
            required: true
          }, {
            name: 'message',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'applepayResponse',
            typeInfo: '.ApplepayResponse'
          }]
      }, {
        localName: 'EnhancedAuthResponse',
        typeName: null,
        propertyInfos: [{
            name: 'fundingSource',
            typeInfo: '.EnhancedAuthResponse.FundingSource'
          }, {
            name: 'affluence',
            typeInfo: '.AffluenceTypeEnum'
          }, {
            name: 'issuerCountry'
          }, {
            name: 'cardProductType',
            typeInfo: '.CardProductTypeEnum'
          }, {
            name: 'virtualAccountNumber',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'RecyclingType',
        typeName: 'recyclingType',
        propertyInfos: [{
            name: 'recycleAdvice',
            typeInfo: '.RecycleAdviceType'
          }, {
            name: 'recycleEngineActive',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'DriversLicenseInfo',
        typeName: 'driversLicenseInfo',
        propertyInfos: [{
            name: 'licenseNumber',
            required: true
          }, {
            name: 'state'
          }, {
            name: 'dateOfBirth'
          }]
      }, {
        localName: 'AccountUpdater',
        typeName: null,
        propertyInfos: [{
            name: 'originalCardTokenInfo',
            required: true,
            typeInfo: '.CardTokenInfoType'
          }, {
            name: 'newCardTokenInfo',
            required: true,
            typeInfo: '.CardTokenInfoType'
          }, {
            name: 'originalCardInfo',
            required: true,
            typeInfo: '.CardAccountInfoType'
          }, {
            name: 'newCardInfo',
            required: true,
            typeInfo: '.CardAccountInfoType'
          }, {
            name: 'extendedCardResponse',
            typeInfo: '.ExtendedCardResponseType'
          }, {
            name: 'originalTokenInfo',
            required: true,
            typeInfo: '.EcheckTokenInfoType'
          }, {
            name: 'newTokenInfo',
            required: true,
            typeInfo: '.EcheckTokenInfoType'
          }, {
            name: 'originalAccountInfo',
            required: true,
            typeInfo: '.EcheckAccountInfoType'
          }, {
            name: 'newAccountInfo',
            required: true,
            typeInfo: '.EcheckAccountInfoType'
          }]
      }, {
        localName: 'RecycleAdviceType',
        typeName: 'recycleAdviceType',
        propertyInfos: [{
            name: 'recycleAdviceEnd',
            required: true
          }, {
            name: 'nextRecycleTime',
            required: true,
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'Credit.Paypal',
        typeName: null,
        propertyInfos: [{
            name: 'payerEmail',
            required: true
          }, {
            name: 'payerId',
            required: true
          }]
      }, {
        localName: 'ProcessingInstructions',
        typeName: null,
        propertyInfos: [{
            name: 'bypassVelocityCheck',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'CaptureGivenAuthResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'AuthReversal',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'amount',
            typeInfo: 'Integer'
          }, {
            name: 'surchargeAmount',
            typeInfo: 'Integer'
          }, {
            name: 'payPalNotes'
          }, {
            name: 'actionReason'
          }]
      }, {
        localName: 'FraudCheckResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'response',
            required: true
          }, {
            name: 'message',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'advancedFraudResults',
            typeInfo: '.AdvancedFraudResultsType'
          }]
      }, {
        localName: 'CreateDiscountType',
        typeName: 'createDiscountType',
        propertyInfos: [{
            name: 'discountCode',
            required: true
          }, {
            name: 'name',
            required: true
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'startDate',
            required: true,
            typeInfo: 'Date'
          }, {
            name: 'endDate',
            required: true,
            typeInfo: 'Date'
          }]
      }, {
        localName: 'DeactivateReversalResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'CancelSubscriptionResponse',
        typeName: null,
        baseTypeInfo: '.RecurringTransactionResponseType',
        propertyInfos: [{
            name: 'subscriptionId',
            required: true,
            typeInfo: 'Long'
          }]
      }, {
        localName: 'AmexAggregatorData',
        typeName: null,
        propertyInfos: [{
            name: 'sellerId',
            required: true
          }, {
            name: 'sellerMerchantCategoryCode',
            required: true
          }]
      }, {
        localName: 'HealthcareIIAS',
        typeName: null,
        propertyInfos: [{
            name: 'healthcareAmounts',
            required: true,
            typeInfo: '.HealthcareAmounts'
          }, {
            name: 'iiasFlag',
            required: true,
            elementName: 'IIASFlag',
            typeInfo: '.IIASFlagType'
          }]
      }, {
        localName: 'ExtendedCardResponseType',
        typeName: 'extendedCardResponseType',
        propertyInfos: [{
            name: 'message',
            required: true
          }, {
            name: 'code',
            required: true
          }]
      }, {
        localName: 'EcheckTokenInfoType',
        typeName: 'echeckTokenInfoType',
        propertyInfos: [{
            name: 'accType',
            required: true,
            typeInfo: '.EcheckAccountTypeEnum'
          }, {
            name: 'litleToken',
            required: true
          }, {
            name: 'routingNum',
            required: true
          }]
      }, {
        localName: 'ActivateReversalResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'EcheckTokenType',
        typeName: 'echeckTokenType',
        propertyInfos: [{
            name: 'litleToken',
            required: true
          }, {
            name: 'routingNum',
            required: true
          }, {
            name: 'accType',
            required: true,
            typeInfo: '.EcheckAccountTypeEnum'
          }, {
            name: 'checkNum'
          }]
      }, {
        localName: 'AccountInfoType',
        typeName: 'accountInfoType',
        propertyInfos: [{
            name: 'type',
            required: true,
            values: ['MC', 'VI', 'AX', 'DC', 'DI', 'PP', 'JC', 'BL', 'EC', 'GC', '']
          }, {
            name: 'number'
          }]
      }, {
        localName: 'Capture',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroupAndPartial',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'amount',
            typeInfo: 'Integer'
          }, {
            name: 'surchargeAmount',
            typeInfo: 'Integer'
          }, {
            name: 'enhancedData',
            typeInfo: '.EnhancedData'
          }, {
            name: 'processingInstructions',
            typeInfo: '.ProcessingInstructions'
          }, {
            name: 'payPalOrderComplete',
            typeInfo: 'Boolean'
          }, {
            name: 'payPalNotes'
          }]
      }, {
        localName: 'RecurringTransactionResponseType',
        typeName: 'recurringTransactionResponseType',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'response',
            required: true
          }, {
            name: 'message',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }]
      }, {
        localName: 'Sale',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'secondaryAmount',
            typeInfo: 'Integer'
          }, {
            name: 'surchargeAmount',
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'customerInfo',
            typeInfo: '.CustomerInfo'
          }, {
            name: 'billToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'shipToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'applepay',
            required: true,
            typeInfo: '.ApplepayType'
          }, {
            name: 'paypage',
            required: true,
            typeInfo: '.CardPaypageType'
          }, {
            name: 'token',
            required: true,
            typeInfo: '.CardTokenType'
          }, {
            name: 'paypal',
            required: true,
            typeInfo: '.PayPal'
          }, {
            name: 'card',
            required: true,
            typeInfo: '.CardType'
          }, {
            name: 'mpos',
            required: true,
            typeInfo: '.MposType'
          }, {
            name: 'billMeLaterRequest',
            typeInfo: '.BillMeLaterRequest'
          }, {
            name: 'cardholderAuthentication',
            typeInfo: '.FraudCheckType'
          }, {
            name: 'fraudCheck',
            typeInfo: '.FraudCheckType'
          }, {
            name: 'customBilling',
            typeInfo: '.CustomBilling'
          }, {
            name: 'taxType',
            typeInfo: '.GovtTaxTypeEnum'
          }, {
            name: 'enhancedData',
            typeInfo: '.EnhancedData'
          }, {
            name: 'processingInstructions',
            typeInfo: '.ProcessingInstructions'
          }, {
            name: 'pos',
            typeInfo: '.Pos'
          }, {
            name: 'payPalOrderComplete',
            typeInfo: 'Boolean'
          }, {
            name: 'payPalNotes'
          }, {
            name: 'amexAggregatorData',
            typeInfo: '.AmexAggregatorData'
          }, {
            name: 'allowPartialAuth',
            typeInfo: 'Boolean'
          }, {
            name: 'healthcareIIAS',
            typeInfo: '.HealthcareIIAS'
          }, {
            name: 'filtering',
            typeInfo: '.FilteringType'
          }, {
            name: 'merchantData',
            typeInfo: '.MerchantDataType'
          }, {
            name: 'recyclingRequest',
            typeInfo: '.RecyclingRequestType'
          }, {
            name: 'fraudFilterOverride',
            typeInfo: 'Boolean'
          }, {
            name: 'recurringRequest',
            typeInfo: '.RecurringRequestType'
          }, {
            name: 'litleInternalRecurringRequest',
            typeInfo: '.LitleInternalRecurringRequestType'
          }, {
            name: 'debtRepayment',
            typeInfo: 'Boolean'
          }, {
            name: 'advancedFraudChecks',
            typeInfo: '.AdvancedFraudChecksType'
          }, {
            name: 'wallet',
            typeInfo: '.Wallet'
          }]
      }, {
        localName: 'CardType',
        typeName: 'cardType',
        propertyInfos: [{
            name: 'track',
            required: true
          }, {
            name: 'type',
            required: true,
            values: ['MC', 'VI', 'AX', 'DC', 'DI', 'PP', 'JC', 'BL', 'EC', 'GC', '']
          }, {
            name: 'number'
          }, {
            name: 'expDate'
          }, {
            name: 'cardValidationNum'
          }]
      }, {
        localName: 'CancelSubscription',
        typeName: null,
        baseTypeInfo: '.RecurringTransactionType',
        propertyInfos: [{
            name: 'subscriptionId',
            required: true,
            typeInfo: 'Long'
          }]
      }, {
        localName: 'LineItemData',
        typeName: null,
        propertyInfos: [{
            name: 'itemSequenceNumber',
            typeInfo: 'Integer'
          }, {
            name: 'itemDescription',
            required: true
          }, {
            name: 'productCode'
          }, {
            name: 'quantity',
            typeInfo: 'Decimal'
          }, {
            name: 'unitOfMeasure'
          }, {
            name: 'taxAmount',
            typeInfo: 'Integer'
          }, {
            name: 'lineItemTotal',
            typeInfo: 'Integer'
          }, {
            name: 'lineItemTotalWithTax',
            typeInfo: 'Integer'
          }, {
            name: 'itemDiscountAmount',
            typeInfo: 'Integer'
          }, {
            name: 'commodityCode'
          }, {
            name: 'unitCost',
            typeInfo: 'Decimal'
          }, {
            name: 'detailTaxes',
            minOccurs: 0,
            maxOccurs: 6,
            collection: true,
            elementName: 'detailTax',
            typeInfo: '.DetailTax'
          }]
      }, {
        localName: 'DeleteDiscountType',
        typeName: 'deleteDiscountType',
        propertyInfos: [{
            name: 'discountCode',
            required: true
          }]
      }, {
        localName: 'MposType',
        typeName: 'mposType',
        propertyInfos: [{
            name: 'ksn',
            required: true
          }, {
            name: 'formatId',
            required: true
          }, {
            name: 'encryptedTrack',
            required: true
          }, {
            name: 'track1Status',
            required: true,
            typeInfo: 'Int'
          }, {
            name: 'track2Status',
            required: true,
            typeInfo: 'Int'
          }]
      }, {
        localName: 'FraudCheckType',
        typeName: 'fraudCheckType',
        propertyInfos: [{
            name: 'authenticationValue',
            typeInfo: 'Base64Binary'
          }, {
            name: 'authenticationTransactionId',
            typeInfo: 'Base64Binary'
          }, {
            name: 'customerIpAddress'
          }, {
            name: 'authenticatedByMerchant',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'EcheckAccountInfoType',
        typeName: 'echeckAccountInfoType',
        propertyInfos: [{
            name: 'accType',
            required: true,
            typeInfo: '.EcheckAccountTypeEnum'
          }, {
            name: 'accNum',
            required: true
          }, {
            name: 'routingNum',
            required: true
          }]
      }, {
        localName: 'EcheckSale',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'orderId',
            required: true
          }, {
            name: 'verify',
            typeInfo: 'Boolean'
          }, {
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'amount',
            typeInfo: 'Integer'
          }, {
            name: 'secondaryAmount',
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'billToAddress',
            required: true,
            typeInfo: '.Contact'
          }, {
            name: 'shipToAddress',
            typeInfo: '.Contact'
          }, {
            name: 'echeckOrEcheckToken',
            required: true,
            mixed: false,
            allowDom: false,
            typeInfo: 'AnyType',
            type: 'elementRef'
          }, {
            name: 'customBilling',
            typeInfo: '.CustomBilling'
          }, {
            name: 'merchantData',
            typeInfo: '.MerchantDataType'
          }]
      }, {
        localName: 'UpdatePlanResponse',
        typeName: null,
        baseTypeInfo: '.RecurringTransactionResponseType',
        propertyInfos: [{
            name: 'planCode',
            required: true
          }]
      }, {
        localName: 'BalanceInquiryResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }]
      }, {
        localName: 'CaptureResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId'
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'accountUpdater',
            typeInfo: '.AccountUpdater'
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }, {
            name: 'duplicate',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'duplicate'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'BillMeLaterResponseData',
        typeName: null,
        propertyInfos: [{
            name: 'bmlMerchantId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'promotionalOfferCode'
          }, {
            name: 'approvedTermsCode',
            typeInfo: 'Int'
          }, {
            name: 'creditLine',
            typeInfo: 'Integer'
          }, {
            name: 'addressIndicator'
          }, {
            name: 'loanToValueEstimator'
          }, {
            name: 'riskEstimator'
          }, {
            name: 'riskQueueAssignment'
          }]
      }, {
        localName: 'ApplepayType',
        typeName: 'applepayType',
        propertyInfos: [{
            name: 'data',
            required: true
          }, {
            name: 'header',
            required: true,
            typeInfo: '.ApplepayHeaderType'
          }, {
            name: 'signature',
            required: true
          }, {
            name: 'version',
            required: true
          }]
      }, {
        localName: 'LoadResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }, {
            name: 'duplicate',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'duplicate'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'UnloadResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'fraudResult',
            typeInfo: '.FraudResult'
          }, {
            name: 'giftCardResponse',
            typeInfo: '.GiftCardResponse'
          }, {
            name: 'duplicate',
            typeInfo: 'Boolean',
            attributeName: {
              localPart: 'duplicate'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'AdvancedFraudChecksType',
        typeName: 'advancedFraudChecksType',
        propertyInfos: [{
            name: 'threatMetrixSessionId',
            required: true,
            typeInfo: 'Token'
          }]
      }, {
        localName: 'CustomerInfo',
        typeName: null,
        propertyInfos: [{
            name: 'ssn'
          }, {
            name: 'dob',
            typeInfo: 'Date'
          }, {
            name: 'customerRegistrationDate',
            typeInfo: 'Date'
          }, {
            name: 'customerType',
            values: ['New', 'Existing']
          }, {
            name: 'incomeAmount',
            typeInfo: 'Long'
          }, {
            name: 'incomeCurrency',
            typeInfo: '.CurrencyCodeEnum'
          }, {
            name: 'customerCheckingAccount',
            typeInfo: 'Boolean'
          }, {
            name: 'customerSavingAccount',
            typeInfo: 'Boolean'
          }, {
            name: 'employerName'
          }, {
            name: 'customerWorkTelephone'
          }, {
            name: 'residenceStatus',
            values: ['Own', 'Rent', 'Other']
          }, {
            name: 'yearsAtResidence',
            typeInfo: 'Int'
          }, {
            name: 'yearsAtEmployer',
            typeInfo: 'Int'
          }]
      }, {
        localName: 'EnhancedAuthResponse.FundingSource',
        typeName: null,
        propertyInfos: [{
            name: 'type',
            required: true,
            typeInfo: '.FundingSourceTypeEnum'
          }, {
            name: 'availableBalance',
            required: true
          }, {
            name: 'reloadable'
          }, {
            name: 'prepaidCardType'
          }]
      }, {
        localName: 'FilteringType',
        typeName: 'filteringType',
        propertyInfos: [{
            name: 'prepaid',
            typeInfo: 'Boolean'
          }, {
            name: 'international',
            typeInfo: 'Boolean'
          }, {
            name: 'chargeback',
            typeInfo: 'Boolean'
          }]
      }, {
        localName: 'EcheckVerificationResponse',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            required: true,
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'response',
            required: true
          }, {
            name: 'responseTime',
            required: true,
            typeInfo: 'DateTime'
          }, {
            name: 'message',
            required: true
          }, {
            name: 'postDate',
            typeInfo: 'Date'
          }, {
            name: 'tokenResponse',
            typeInfo: '.TokenResponseType'
          }]
      }, {
        localName: 'EcheckVerification',
        typeName: null,
        baseTypeInfo: '.TransactionTypeWithReportGroup',
        propertyInfos: [{
            name: 'litleTxnId',
            typeInfo: 'Long'
          }, {
            name: 'orderId',
            required: true
          }, {
            name: 'amount',
            required: true,
            typeInfo: 'Integer'
          }, {
            name: 'orderSource',
            required: true,
            values: ['ecommerce', 'installment', 'mailorder', 'recurring', 'retail', 'telephone', '3dsAuthenticated', '3dsAttempted', 'recurringtel', 'echeckppd', 'applepay']
          }, {
            name: 'billToAddress',
            required: true,
            typeInfo: '.Contact'
          }, {
            name: 'echeckOrEcheckToken',
            required: true,
            mixed: false,
            allowDom: false,
            typeInfo: 'AnyType',
            type: 'elementRef'
          }, {
            name: 'merchantData',
            typeInfo: '.MerchantDataType'
          }]
      }, {
        localName: 'UpdateAddOnType',
        typeName: 'updateAddOnType',
        propertyInfos: [{
            name: 'addOnCode',
            required: true
          }, {
            name: 'name'
          }, {
            name: 'amount',
            typeInfo: 'Integer'
          }, {
            name: 'startDate',
            typeInfo: 'Date'
          }, {
            name: 'endDate',
            typeInfo: 'Date'
          }]
      }, {
        localName: 'MerchantDataType',
        typeName: 'merchantDataType',
        propertyInfos: [{
            name: 'campaign'
          }, {
            name: 'affiliate'
          }, {
            name: 'merchantGroupingId'
          }]
      }, {
        type: 'enumInfo',
        localName: 'PosCapabilityTypeEnum',
        values: ['notused', 'magstripe', 'keyedonly']
      }, {
        type: 'enumInfo',
        localName: 'CardProductTypeEnum',
        values: ['UNKNOWN', 'COMMERCIAL', 'CONSUMER']
      }, {
        type: 'enumInfo',
        localName: 'PosCatLevelEnum',
        values: ['self service']
      }, {
        type: 'enumInfo',
        localName: 'AffluenceTypeEnum',
        values: ['AFFLUENT', 'MASS AFFLUENT']
      }, {
        type: 'enumInfo',
        localName: 'RecycleByTypeEnum',
        values: ['Merchant', 'Litle', 'None']
      }, {
        type: 'enumInfo',
        localName: 'WalletSourceType',
        values: ['MasterPass']
      }, {
        type: 'enumInfo',
        localName: 'IntervalTypeEnum',
        values: ['ANNUAL', 'SEMIANNUAL', 'QUARTERLY', 'MONTHLY', 'WEEKLY']
      }, {
        type: 'enumInfo',
        localName: 'CurrencyCodeEnum',
        values: ['AUD', 'CAD', 'CHF', 'DKK', 'EUR', 'GBP', 'HKD', 'JPY', 'NOK', 'NZD', 'SEK', 'SGD', 'USD']
      }, {
        type: 'enumInfo',
        localName: 'CountryTypeEnum',
        values: ['USA', 'AF', 'AX', 'AL', 'DZ', 'AS', 'AD', 'AO', 'AI', 'AQ', 'AG', 'AR', 'AM', 'AW', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD', 'BB', 'BY', 'BE', 'BZ', 'BJ', 'BM', 'BT', 'BO', 'BQ', 'BA', 'BW', 'BV', 'BR', 'IO', 'BN', 'BG', 'BF', 'BI', 'KH', 'CM', 'CA', 'CV', 'KY', 'CF', 'TD', 'CL', 'CN', 'CX', 'CC', 'CO', 'KM', 'CG', 'CD', 'CK', 'CR', 'CI', 'HR', 'CU', 'CW', 'CY', 'CZ', 'DK', 'DJ', 'DM', 'DO', 'TL', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'ET', 'FK', 'FO', 'FJ', 'FI', 'FR', 'GF', 'PF', 'TF', 'GA', 'GM', 'GE', 'DE', 'GH', 'GI', 'GR', 'GL', 'GD', 'GP', 'GU', 'GT', 'GG', 'GN', 'GW', 'GY', 'HT', 'HM', 'HN', 'HK', 'HU', 'IS', 'IN', 'ID', 'IR', 'IQ', 'IE', 'IM', 'IL', 'IT', 'JM', 'JP', 'JE', 'JO', 'KZ', 'KE', 'KI', 'KP', 'KR', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MO', 'MK', 'MG', 'MW', 'MY', 'MV', 'ML', 'MT', 'MH', 'MQ', 'MR', 'MU', 'YT', 'MX', 'FM', 'MD', 'MC', 'MN', 'MS', 'MA', 'MZ', 'MM', 'NA', 'NR', 'NP', 'NL', 'AN', 'NC', 'NZ', 'NI', 'NE', 'NG', 'NU', 'NF', 'MP', 'NO', 'OM', 'PK', 'PW', 'PS', 'PA', 'PG', 'PY', 'PE', 'PH', 'PN', 'PL', 'PT', 'PR', 'QA', 'RE', 'RO', 'RU', 'RW', 'BL', 'KN', 'LC', 'MF', 'VC', 'WS', 'SM', 'ST', 'SA', 'SN', 'SC', 'SL', 'SG', 'SX', 'SK', 'SI', 'SB', 'SO', 'ZA', 'GS', 'ES', 'LK', 'SH', 'PM', 'SD', 'SR', 'SJ', 'SZ', 'SE', 'CH', 'SY', 'TW', 'TJ', 'TZ', 'TH', 'TG', 'TK', 'TO', 'TT', 'TN', 'TR', 'TM', 'TC', 'TV', 'UG', 'UA', 'AE', 'GB', 'US', 'UM', 'UY', 'UZ', 'VU', 'VA', 'VE', 'VN', 'VG', 'VI', 'WF', 'EH', 'YE', 'ZM', 'ZW', 'RS', 'ME', 'SS']
      }, {
        type: 'enumInfo',
        localName: 'PosCardholderIdTypeEnum',
        values: ['signature', 'pin', 'nopin', 'directmarket']
      }, {
        type: 'enumInfo',
        localName: 'TrialIntervalTypeEnum',
        values: ['MONTH', 'DAY']
      }, {
        type: 'enumInfo',
        localName: 'PosEntryModeTypeEnum',
        values: ['notused', 'keyed', 'track1', 'track2', 'completeread']
      }, {
        type: 'enumInfo',
        localName: 'EcheckAccountTypeEnum',
        values: ['Checking', 'Savings', 'Corporate', 'Corp Savings']
      }, {
        type: 'enumInfo',
        localName: 'GovtTaxTypeEnum',
        values: ['payment', 'fee']
      }, {
        type: 'enumInfo',
        localName: 'FundingSourceTypeEnum',
        values: ['UNKNOWN', 'PREPAID', 'FSA', 'CREDIT', 'DEBIT']
      }, {
        type: 'enumInfo',
        localName: 'ReloadablePrepaidTypeEnum',
        values: ['UNKNOWN', 'YES', 'NO']
      }, {
        type: 'enumInfo',
        localName: 'IIASFlagType',
        values: ['Y']
      }],
    elementInfos: [{
        typeInfo: '.AuthInformation',
        elementName: 'authInformation'
      }, {
        typeInfo: '.Authorization',
        elementName: 'authorization',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.UpdateSubscriptionResponse',
        elementName: 'updateSubscriptionResponse',
        substitutionHead: 'recurringTransactionResponse'
      }, {
        typeInfo: '.UnloadReversalResponse',
        elementName: 'unloadReversalResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.VirtualGiftCardResponse',
        elementName: 'virtualGiftCardResponse'
      }, {
        typeInfo: '.LoadResponse',
        elementName: 'loadResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.EcheckSalesResponse',
        elementName: 'echeckSalesResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.EcheckRedepositResponse',
        elementName: 'echeckRedepositResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.EcheckSale',
        elementName: 'echeckSale',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.DeactivateReversalResponse',
        elementName: 'deactivateReversalResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.SaleResponse',
        elementName: 'saleResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.Wallet',
        elementName: 'wallet'
      }, {
        typeInfo: '.LoadReversalResponse',
        elementName: 'loadReversalResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.BalanceInquiryResponse',
        elementName: 'balanceInquiryResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.CreatePlan',
        elementName: 'createPlan',
        substitutionHead: 'recurringTransaction'
      }, {
        typeInfo: '.EnhancedData',
        elementName: 'enhancedData'
      }, {
        typeInfo: '.LineItemData',
        elementName: 'lineItemData'
      }, {
        typeInfo: '.RecurringTransactionResponseType',
        elementName: 'recurringTransactionResponse'
      }, {
        typeInfo: '.UpdateCardValidationNumOnToken',
        elementName: 'updateCardValidationNumOnToken',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.DetailTax',
        elementName: 'detailTax'
      }, {
        typeInfo: '.ApplepayResponse',
        elementName: 'applepayResponse'
      }, {
        typeInfo: '.UpdateSubscription',
        elementName: 'updateSubscription',
        substitutionHead: 'recurringTransaction'
      }, {
        typeInfo: '.RefundReversalResponse',
        elementName: 'refundReversalResponse',
        substitutionHead: 'transactionResponse'
      }, {
        elementName: 'bmlProductType'
      }, {
        typeInfo: '.FraudCheckResponse',
        elementName: 'fraudCheckResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.AuthorizationResponse',
        elementName: 'authorizationResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.CaptureGivenAuthResponse',
        elementName: 'captureGivenAuthResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.TransactionTypeWithReportGroup',
        elementName: 'transactionResponse'
      }, {
        typeInfo: '.CaptureGivenAuth',
        elementName: 'captureGivenAuth',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.Contact',
        elementName: 'billToAddress'
      }, {
        typeInfo: '.AuthReversalResponse',
        elementName: 'authReversalResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.CustomBilling',
        elementName: 'customBilling'
      }, {
        typeInfo: '.HealthcareAmounts',
        elementName: 'healthcareAmounts'
      }, {
        typeInfo: '.Sale',
        elementName: 'sale',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.Load',
        elementName: 'load',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.AuthReversal',
        elementName: 'authReversal',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.FraudCheck',
        elementName: 'fraudCheck',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.Authentication',
        elementName: 'authentication'
      }, {
        typeInfo: '.ForceCapture',
        elementName: 'forceCapture',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.ActivateResponse',
        elementName: 'activateResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.EcheckVerificationResponse',
        elementName: 'echeckVerificationResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.ForceCaptureResponse',
        elementName: 'forceCaptureResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.CreditResponse',
        elementName: 'creditResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.BalanceInquiry',
        elementName: 'balanceInquiry',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.EcheckRedeposit',
        elementName: 'echeckRedeposit',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.BillMeLaterRequest',
        elementName: 'billMeLaterRequest'
      }, {
        typeInfo: '.FraudResult',
        elementName: 'fraudResult'
      }, {
        typeInfo: '.TransactionType',
        elementName: 'transaction'
      }, {
        typeInfo: '.Capture',
        elementName: 'capture',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.HealthcareIIAS',
        elementName: 'healthcareIIAS'
      }, {
        typeInfo: '.EcheckCreditResponse',
        elementName: 'echeckCreditResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.GiftCardResponse',
        elementName: 'giftCardResponse'
      }, {
        typeInfo: '.CaptureResponse',
        elementName: 'captureResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.DeactivateResponse',
        elementName: 'deactivateResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.EcheckTokenType',
        elementName: 'echeckToken',
        substitutionHead: 'echeckOrEcheckToken'
      }, {
        typeInfo: '.EnhancedAuthResponse',
        elementName: 'enhancedAuthResponse'
      }, {
        typeInfo: '.UpdatePlanResponse',
        elementName: 'updatePlanResponse',
        substitutionHead: 'recurringTransactionResponse'
      }, {
        typeInfo: '.Credit',
        elementName: 'credit',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.AmexAggregatorData',
        elementName: 'amexAggregatorData'
      }, {
        typeInfo: '.Contact',
        elementName: 'shipToAddress'
      }, {
        typeInfo: '.RecurringTransactionType',
        elementName: 'recurringTransaction'
      }, {
        typeInfo: '.DepositReversalResponse',
        elementName: 'depositReversalResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.Pos',
        elementName: 'pos'
      }, {
        typeInfo: '.UpdateCardValidationNumOnTokenResponse',
        elementName: 'updateCardValidationNumOnTokenResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.CustomerInfo',
        elementName: 'customerInfo'
      }, {
        typeInfo: '.BillMeLaterResponseData',
        elementName: 'billMeLaterResponseData'
      }, {
        typeInfo: '.ActivateReversalResponse',
        elementName: 'activateReversalResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.CancelSubscriptionResponse',
        elementName: 'cancelSubscriptionResponse',
        substitutionHead: 'recurringTransactionResponse'
      }, {
        typeInfo: '.Deactivate',
        elementName: 'deactivate',
        substitutionHead: 'transaction'
      }, {
        typeInfo: 'AnyType',
        elementName: 'echeckOrEcheckToken'
      }, {
        typeInfo: '.Activate',
        elementName: 'activate',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.UpdatePlan',
        elementName: 'updatePlan',
        substitutionHead: 'recurringTransaction'
      }, {
        typeInfo: '.EcheckCredit',
        elementName: 'echeckCredit',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.RegisterTokenResponse',
        elementName: 'registerTokenResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.Unload',
        elementName: 'unload',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.EcheckType',
        elementName: 'echeck',
        substitutionHead: 'echeckOrEcheckToken'
      }, {
        typeInfo: '.AccountUpdater',
        elementName: 'accountUpdater'
      }, {
        typeInfo: '.UnloadResponse',
        elementName: 'unloadResponse',
        substitutionHead: 'transactionResponse'
      }, {
        typeInfo: '.CancelSubscription',
        elementName: 'cancelSubscription',
        substitutionHead: 'recurringTransaction'
      }, {
        typeInfo: '.EcheckVerification',
        elementName: 'echeckVerification',
        substitutionHead: 'transaction'
      }, {
        typeInfo: '.ProcessingInstructions',
        elementName: 'processingInstructions'
      }, {
        typeInfo: '.CreatePlanResponse',
        elementName: 'createPlanResponse',
        substitutionHead: 'recurringTransactionResponse'
      }, {
        typeInfo: '.RegisterTokenRequestType',
        elementName: 'registerTokenRequest',
        substitutionHead: 'transaction'
      }]
  };
  return {
    litleTransaction_v8_29: litleTransaction_v8_29
  };
};
if (typeof define === 'function' && define.amd) {
  define([], litleTransaction_v8_29_Module_Factory);
}
else {
  var litleTransaction_v8_29_Module = litleTransaction_v8_29_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.litleTransaction_v8_29 = litleTransaction_v8_29_Module.litleTransaction_v8_29;
  }
  else {
    var litleTransaction_v8_29 = litleTransaction_v8_29_Module.litleTransaction_v8_29;
  }
}